# Change these first
owner: Space-Turtle0 # Your GitHub username
repo: SS-Hosting # Your GitHub repository name

# Add your sites here
sites:
  - name: BugBot
    url: $REPL_BUG
    icon: https://st2.depositphotos.com/5266903/11380/v/950/depositphotos_113809396-stock-illustration-system-setup-flat-rounded-vector.jpg
  - name: EvalBot
    url: $REPL_EVAL
    icon: https://community.infoblox.com/t5/image/serverpage/image-id/2195iA290BF7E3BA6064D/image-size/large/is-moderation-mode/true?v=1.0&px=999

status-website:
  baseUrl: /SS-Hosting
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: School-Simplified Status Page 
  introTitle: "Monitoring All Bots!"
  introMessage: Checking for any downtime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
